language: java
env:
  global:
    - CATALINA_PID=/tmp/tomcat.pid
    - CATALINA_OUT=/tmp/tomcat.log
    - CATALINA_OPTS="-XX:MaxPermSize=256M -DUAA_PROFILE=local"
  matrix:
    - SPRING_PROFILES=default,coverage
    - SPRING_PROFILES=default,saml,coverage
before_install:
  - git pull --unshallow
  - wget -O tomcat.tar.gz http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.52/bin/apache-tomcat-7.0.52.tar.gz
  - unset GEM_PATH # for compatibility with the maven-sass-plugin
install:
  - $TRAVIS_BUILD_DIR/.apply_spring_profiles_to_login_yaml.sh $SPRING_PROFILES
  - cat login-server/src/main/resources/login.yml
  - mvn test-compile -P coverage --quiet
  - mkdir -p target/tomcat
  - tar zxf tomcat.tar.gz -C target/tomcat --strip-components 1
  - export WEBAPPS_DIR=$TRAVIS_BUILD_DIR/target/tomcat/webapps
  - rm -rf $WEBAPPS_DIR/*
  - export IDENTITY_VERSION=`mvn help:evaluate -Dexpression=project.parent.version | grep -v "\[" | tail -n 1`
  - mvn dependency:copy -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-uaa:$IDENTITY_VERSION:war -DoutputDirectory=$WEBAPPS_DIR --quiet
  - mv $WEBAPPS_DIR/cloudfoundry-identity-uaa-*.war $WEBAPPS_DIR/uaa.war
  - mvn dependency:copy -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-app:$IDENTITY_VERSION:war -DoutputDirectory=$WEBAPPS_DIR --quiet
  - mv $WEBAPPS_DIR/cloudfoundry-identity-app-*.war $WEBAPPS_DIR/app.war
  - mvn dependency:copy -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-api:$IDENTITY_VERSION:war -DoutputDirectory=$WEBAPPS_DIR --quiet
  - mv $WEBAPPS_DIR/cloudfoundry-identity-api-*.war $WEBAPPS_DIR/api.war
before_script:
  - $TRAVIS_BUILD_DIR/.cobertura-instrument.sh
  - mvn -Dwar.exploded.dir=$WEBAPPS_DIR/login -pl login-server war:exploded -P coverage
  - export CI_LOGGING_CONFIG=$TRAVIS_BUILD_DIR/login-server/src/test/resources/log4j_ci.properties
script:
  - ./.run-script.sh start
  - mvn -Dspring.profiles.active=${SPRING_PROFILES} -Dlogging.config=file://$CI_LOGGING_CONFIG -Dlog4j.configuration=$CI_LOGGING_CONFIG verify -DforceIntegrationTests -DfailIfNoTests=false -Dtest="org.cloudfoundry.identity.uaa.login.feature.*" -P coverage
  - curl -v -X POST http://localhost:8080/login/healthz/coverage/flush
  - ./.run-script.sh stop
  - mvn -Dspring.profiles.active=${SPRING_PROFILES} -Dlogging.config=file://$CI_LOGGING_CONFIG -Dlog4j.configuration=$CI_LOGGING_CONFIG test -P coverage
after_success:
  - $TRAVIS_BUILD_DIR/.cobertura-report.sh
  - mvn -pl login-server coveralls:cobertura
after_failure:
  - cat $CATALINA_OUT
after_script:
  - rm -rf tomcat
  - rm -f tomcat.tar.gz
